java:
  applicationPort: 4750
  image: 'hmctspublic.azurecr.io/civil/sdt-commissioning:latest'
  ingressHost: civil-sdt-commissioning-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: civil
  keyVaults:
    civil-sdt:
      secrets:
        - name: civil-sdt-appinsights-connection-string
          alias: APPINSIGHTS_CONNECTION_STRING
  environment:
